version: "3.8"

services:
  fastapi:
    build: .
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    restart: always

  postgres:
    build: ./postgres
    ports:
      - "5432:5432"  # Expose publicly
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - pg_data:/var/lib/postgresql@14/data
  
  # adminer:
  #   image: adminer
  #   restart: always
  #   ports:
  #     - 8080:8080
  
  # mageai:
  #   image: mageai/mageai:latest
  #   command: mage start ${PROJECT_NAME}
  #   # build: ./mageai
  #   ports:
  #     - 6789:6789
  #   environment:
  #     REQUIRE_USER_AUTHENTICATION: ${REQUIRE_USER_AUTHENTICATION}
  #     USER_CODE_PATH: /home/src/${PROJECT_NAME}
  #   volumes:
  #     - mageai_data:/home/src/
  #   restart: on-failure:5

volumes:
  pg_data:
  mageai_data:
